services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: pyconapac
      POSTGRES_USER: pyconapac
      POSTGRES_PASSWORD: pyconapac
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data/

volumes:
  postgres:
