{
 "title": "AI Agent",
 "time": { "from": "2024-12-01T15:57:22.799Z", "to": "2024-12-01T15:58:36.816Z" },
 "panels": [
  {
   "title": "P95 Gen AI Client Operation ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gen_ai_client_operation_duration_seconds_bucket{\n    }[$__rate_interval])) \nby (le, gen_ai_response_model))",
     "legendFormat": "{{gen_ai_response_model}}"
    }
   ]
  },
  {
   "title": "P95 Gen AI Client Token Usage ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gen_ai_client_token_usage_bucket{\n    }[$__rate_interval])) \nby (le, gen_ai_response_model))",
     "legendFormat": "{{gen_ai_response_model}}"
    }
   ]
  },
  {
   "title": "Total Token Usage Past 1h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gen_ai_client_token_usage_sum{exported_job=\"testing-openllmetry\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Token Usage Past 10m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gen_ai_client_token_usage_sum{exported_job=\"testing-openllmetry\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Token Usage Past 10m",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(gen_ai_client_token_usage_sum[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency [ms]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(duration_milliseconds_bucket{}[$__rate_interval])) by (span_name, le))",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "Total Calls",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(calls_total{\n    service_name=\"testing-openllmetry\",\n    }[$__interval])",
     "legendFormat": "{{span_name}}"
    }
   ]
  }
 ]
}